### ISSUE TITLE
[Arbeitspaket] Liste mit Comcave Standorten anlegen

### ISSUE THREAD

**Issue by HolgerSin** [ComcaveTeamwork/CTP_01_TableReader#27]
**Betroffene Dateien**

Datei im Markdown Format ist neu zu erstellen

**Beschreibung des Arbeitspakets**

neue Datei erstellen, in der folgende Einträge vorhanden sind:
Standort   |   PLZ   |   Bundesland
---|---|---
Bielefeld  | 33613 | NRW

**Comment by Hostmisha1** [comment]
-Standort ist bereits in der Liste vorhanden.
-Handynummer und E-Mail Adresse als Kontaktaufnahme hinzufügen?
-Aktueller Standort (in hinsicht auf deine APP würde ich die entfernung zur person hinzufügen in KM) und einen extra tabellenplatz für die Zukunft offen lassen

**Comment by HolgerSin** [comment]
@Hostmisha1 Bitte bei der Bearbeitung dieses Arbeitspakets genau an die Vorgabe halten, und die Tabelle so erstellen wie vorgegeben (3 Spalten, 2 Zeilen). Außerdem versuch bitte mal den Workflow so wie im Wiki beschrieben umzusetzen. Das ist zwar unverhältnismäßig kompliziert für so eine kleine Tabelle, aber um halt mal das Prinzip umzusetzen.
Die Tabelle mit den 20 Zeilen die du schon vorbereitet hast, kannst du gerne im ForStarters Repo erstellen.

**Comment by Hostmisha1** [comment]
Ok also rebriefing:
1) Neue Datei im .md format erstellen :  ComcaveTeamwork /
CTP_01_TableReader/"CC_Standort.md" als  neue branch mit patch 1.
2) Folgenden Inhalt als Liste erstellen :
<html><body>


Standort | PLZ | Bundesland
-- | -- | --
Bielefeld | 33613 | NRW


</body>
</html>
3) Thats all Folks?

**Comment by HolgerSin** [comment]
Korrekt, weitere Zeilen mit anderen Standorten folgen in anderen Arbeitspaketen.

**Comment by HolgerSin** [comment]
Du könntest noch das Label "in Bearbeitung" zu diesem issue hinzufügen, und dieses issue mit deinem PR verlinken.
