### ISSUE TITLE
[Arbeitspaket] ordered List einfügen

### ISSUE THREAD

**Issue by HolgerSin** [ComcaveTeamwork/CTP_01_TableReader#39]
**Betroffene Dateien**
tableReader.html
EDIT: hier war zuerst tableReader.js genannt, gemeint war tableReader.html

**Beschreibung des Arbeitspakets**

Neben der unordered List, die im Augenblick auf Button Druck ausgegeben wird, soll eine ordered List (HTML Element `<ol>`) mit folgendem statischem Inhalt angezeigt werden:
1. Lorem
2. Ipsum
3. Dolor

**Zusatzinformationen**

Die ordered list wenn möglich rechts neben der unordered list ausgeben, ggf. auch darunter wenn daneben zu schwierig ist.
Optional: Button "update ordered list" einfügen (ohne Funktionalität)

**Abhängigkeiten**

Keine

### Wichtig
Bitte den im Wiki beschriebenen [Workflow](https://github.com/ComcaveTeamwork/CTP_01_TableReader/wiki/Workflow) einhalten

**Comment by Indu1284** [comment]
Ich möchte in diese issue Bearbeiten

**Comment by Hostmisha1** [comment]
sure you can have it

**Comment by Indu1284** [comment]
Ordered List eingefüngt
