### ISSUE TITLE
[Arbeitspaket] "Datei auswählen" Button mit Funktionalität versehen

### ISSUE THREAD

**Issue by HolgerSin** [ComcaveTeamwork/CTP_01_TableReader#63]
**Betroffene Dateien**

tableReader.html, tableReader.js

**Beschreibung des Arbeitspakets**

Bei Klick auf den Button "Datei auswählen" soll sich ein Dateiauswahldialog öffnen, um die einzulesende Datei auszuwählen.

**Zusatzinformationen**

Den Pfad der ausgewählten Datei in der Konsole ausgeben

**Abhängigkeiten**

Keine

### Wichtig
Bitte den im Wiki beschriebenen [Workflow](https://github.com/ComcaveTeamwork/CTP_01_TableReader/wiki/Workflow) einhalten

**Comment by Indu1284** [comment]
I would like to work in this issue.

**Comment by fatihkoeksal** [comment]
> I would like to work in this issue.

of course, why not? It will be great working with you @Indu1284

**Comment by Indu1284** [comment]
Thank you  @fatihkoeksal

**Comment by fatihkoeksal** [comment]
i realise later on that we are not working together if we work another branches, anyway xD

**Comment by HolgerSin** [comment]
Of course it's up to you whether you want to work in parallel independent of each other or cooperate more closely, as you like :-)
